# Generated by Django 5.2.17 on 2026-10-01 16:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectplan_projectstage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日志日期')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='完成内容')),
                ('details', models.TextField(blank=True, default='', verbose_name='过程细节')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='结论')),
                ('next_step', models.TextField(blank=True, default='', verbose_name='下一步')),
                ('blocker', models.TextField(blank=True, default='', verbose_name='阻塞')),
                ('source', models.CharField(choices=[('manual', '人工'), ('agent', 'Agent'), ('imported', '导入')], default='manual', max_length=12, verbose_name='来源')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklogs', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='projects.project', verbose_name='项目')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='projects.projectstage', verbose_name='所属阶段')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', '-date'], name='worklogs_wo_project_cf059e_idx'), models.Index(fields=['author', '-date'], name='worklogs_wo_author__8d07bf_idx')],
            },
        ),
    ]
