# Generated by Django 5.2.17 on 2026-09-09 15:37

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('identifier', models.CharField(help_text='2-5 位大写字母数字，用于 Issue 前缀（如 AMI-1），工作区内唯一', max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_identifier', message='identifier 格式不正确，应为 2-5 位大写字母数字。', regex=re.compile('^[A-Z][A-Z0-9]{1,4}$'))], verbose_name='标识符')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('issue_sequence', models.PositiveIntegerField(default=0, verbose_name='Issue 序号计数器')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace', verbose_name='工作区')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField(choices=[(20, '管理员'), (15, '成员'), (5, '只读成员')], default=15, verbose_name='角色')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', '-created_at'], name='projects_pr_workspa_8c9015_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'identifier'), name='uniq_project_identifier_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'project'], name='projects_pr_user_id_1d5a3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
    ]
