# Generated by Django 5.2.17 on 2026-10-01 15:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='GLOBAL PLAN', max_length=120, verbose_name='计划标题')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='projects.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('name', models.CharField(max_length=120, verbose_name='阶段名')),
                ('goal', models.TextField(blank=True, default='', verbose_name='阶段目标')),
                ('weight', models.PositiveIntegerField(default=1, help_text='计算项目总进度时的权重', verbose_name='权重')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='进度(0-100)')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前阶段')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.projectplan', verbose_name='所属计划')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['plan', 'order'], name='projects_pr_plan_id_4265f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'order'), name='uniq_stage_order_per_plan'), models.UniqueConstraint(fields=('plan', 'name'), name='uniq_stage_name_per_plan')],
            },
        ),
    ]
