# Generated by Django 5.2.17 on 2026-10-01 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='如：本地编码 Agent', max_length=80, verbose_name='名称')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='令牌哈希')),
                ('scopes', models.JSONField(default=list, verbose_name='权限白名单')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='吊销时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tokens', to=settings.AUTH_USER_MODEL, verbose_name='持有人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, verbose_name='幂等键')),
                ('action', models.CharField(max_length=60, verbose_name='动作')),
                ('status_code', models.PositiveIntegerField(verbose_name='首次状态码')),
                ('response', models.JSONField(default=dict, verbose_name='首次响应体')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency', to='agents.agenttoken', verbose_name='令牌')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('token', 'key', 'action'), name='uniq_idempotency_per_token_action')],
            },
        ),
    ]
