# Generated by Django 5.2.17 on 2026-10-02 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('issues', '0004_remove_issue_issues_issu_project_3afdd2_idx_and_more'),
        ('projects', '0002_projectplan_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='会话标题')),
                ('status', models.CharField(choices=[('running', '运行中'), ('done', '完成'), ('failed', '失败'), ('stopped', '人工停止')], default='running', max_length=12, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='projects.project', verbose_name='项目')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='issues.issue', verbose_name='关联任务')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='agents.agenttoken', verbose_name='发起令牌')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='agents_agen_project_8a78f4_idx')],
            },
        ),
    ]
