# Generated by Django 5.2.17 on 2026-09-09 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('group', models.CharField(choices=[('backlog', '待规划'), ('unstarted', '未开始'), ('started', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=12, verbose_name='分组')),
                ('color', models.CharField(default='#94a3b8', help_text='#RRGGBB', max_length=9, verbose_name='颜色')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='projects.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_state_name_per_project')],
            },
        ),
    ]
