# Generated by Django 5.2.17 on 2026-09-10 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('color', models.CharField(default='#64748b', help_text='#RRGGBB', max_length=9, verbose_name='颜色')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_id', models.PositiveIntegerField(verbose_name='项目内序号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('priority', models.CharField(choices=[('none', '无'), ('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='none', max_length=10, verbose_name='优先级')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='指派人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('labels', models.ManyToManyField(blank=True, related_name='issues', to='issues.label', verbose_name='标签')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project', verbose_name='项目')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='issues.state', verbose_name='状态')),
            ],
            options={
                'ordering': ['-sequence_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_label_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'state'], name='issues_issu_project_c95ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'priority'], name='issues_issu_project_934913_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', '-created_at'], name='issues_issu_project_3afdd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('project', 'sequence_id'), name='uniq_issue_sequence_per_project'),
        ),
    ]
