# Generated by Django 5.2.17 on 2026-09-10 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_comment'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issue',
            name='issues_issu_project_3afdd2_idx',
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', '-created_at', '-sequence_id'], name='issues_issu_project_c322cb_idx'),
        ),
    ]
