# Generated by Django 5.2.17 on 2026-09-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=40, verbose_name='事件')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='载荷')),
                ('dedupe_key', models.CharField(max_length=160, unique=True, verbose_name='幂等键')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project', verbose_name='项目')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='jobs_notifi_recipie_5480c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('bulk_assign_labels', '批量修改标签')], max_length=40, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('success', '已完成'), ('failure', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='入参')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='结果摘要')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='jobs_taskru_project_1cf4ad_idx'), models.Index(fields=['status'], name='jobs_taskru_status_006f5b_idx')],
            },
        ),
    ]
