# Generated by Django 5.2.17 on 2026-09-10 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0003_comment'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('issue', '任务'), ('comment', '评论'), ('state', '状态'), ('label', '标签'), ('project', '项目'), ('workspace', '工作区'), ('member', '成员')], max_length=16, verbose_name='对象类型')),
                ('entity_id', models.UUIDField(verbose_name='对象 id')),
                ('action', models.CharField(choices=[('created', '创建'), ('updated', '修改'), ('deleted', '删除')], max_length=10, verbose_name='动作')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='issues.issue', verbose_name='任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='项目')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace', verbose_name='工作区')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_ac_project_eaf88d_idx'), models.Index(fields=['issue', '-created_at'], name='activity_ac_issue_i_7307c3_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_ac_entity__564be5_idx')],
            },
        ),
    ]
