# Generated by Django 5.2.17 on 2026-09-09 15:37

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('slug', models.SlugField(help_text='URL 中的租户标识，全局唯一', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='slug 只能包含小写字母、数字和连字符，长度 2-32。', regex=re.compile('^[a-z0-9-]{2,32}$'))], verbose_name='标识')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces_owned', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField(choices=[(20, '管理员'), (15, '成员'), (5, '只读成员')], default=15, verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace', verbose_name='工作区')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'workspace'], name='workspaces__user_id_110b6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_workspace_member')],
            },
        ),
    ]
